package pl.ToolMagazineManager1.ToolMagazineManager1.tool;

public enum GroupName {
    MILLING_CUTTER_SOLID_CARBIDE,
    MILLING_CUTTER_SOLID_HSS,
    MILLING_CUTTER_INDEXABLE_INSERTS,
    TURNING_TOOL_EXTERNAL,
    TURNING_TOOL_INTERNAL,
    DRILL_SOLID_CARBIDE,
    DRILL_SOLID_HSS,
    DRILL_INDEXABLE_INSERTS
}
